### ISSUE TITLE
issue during deployment

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#125]
I was testing the new deployment setup, but received the following error on the `sync_pull` statement:

```
  ...
  Now processing iNaturalist observation #15612654...Observation initially comes from a regular iNaturalist user. Creating a local observation for it. OK
  Now processing iNaturalist observation #15674780...Observation initially comes from a regular iNaturalist user. Creating a local observation for it. OK
  Now processing iNaturalist observation #15680044...Traceback (most recent call last):
  File "manage.py", line 15, in <module>
  execute_from_command_line(sys.argv)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
  utility.execute()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
  self.execute(*args, **cmd_options)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
  output = self.handle(*args, **options)
  File "/opt/python/bundle/2/app/vespawatch/management/commands/sync_pull.py", line 46, in handle
  if inat_observation_comes_from_vespawatch(inat_observation_data['id']):
  File "/opt/python/bundle/2/app/vespawatch/models.py", line 203, in inat_observation_comes_from_vespawatch
  obs_data = get_observation(observation_id=inat_observation_id)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/pyinaturalist/node_api.py", line 38, in get_observation
  r = get_observations(params={'id': observation_id})
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/pyinaturalist/node_api.py", line 52, in get_observations
  return r.json()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
  return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
  return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
  raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   (ElasticBeanstalk::ExternalInvocationError)
```

I think this is about this observation: https://www.inaturalist.org/observations/15680044

**Comment by niconoe** [comment]
Hi @stijnvanhoey, did you encountered the issue several time? I can't reproduce it on my machine (and this specific observation is also imported), so I was wondering if this could have been triggered by a transient error at iNaturalist...

**Comment by stijnvanhoey** [comment]
I can't reproduce the error indeed. Closing for now
