### ISSUE TITLE
`/identification` bug on UAT

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#209]
Current UAT has a template error: `ERROR 2019-03-18 12:59:53,706 log 3933 140428314314496 Internal Server Error: /identification`

Traceback:
 ```
Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/python/current/app/vespawatch/views.py", line 51, in identification
return render(request, 'vespawatch/simple_page_fragment', {'fragment_id': 'identification_page'})
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
content = loader.render_to_string(template_name, context, request, using=using)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
template = get_template(template_name, using=using)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
raise TemplateDoesNotExist(template_name, chain=chain)

django.template.exceptions.TemplateDoesNotExist: vespawatch/simple_page_fragment
```

**Comment by bartaelterman** [comment]
@stijnvanhoey I found a typo. Hope that helps?

**Comment by stijnvanhoey** [comment]
fixed, thanks!
