### ISSUE TITLE
Obs on homepage do not show photo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#210]
@bartaelterman I believe obs photos are now loaded via JS? This works fine on the obs page, but not on the homepage. Probably a script that is not loaded?

**Comment by bartaelterman** [comment]
hmm... works for me. Have you tried rebuilding the JS and running private mode to have the browser cache disabled?

**Comment by stijnvanhoey** [comment]
deployment (see uat.vespawatch.be) of latest master is resulting in missing images, I checked the logs:

```
ERROR 2019-03-25 08:51:06,917 log 3243 139943907104512 Internal Server Error: /api/individuals/38742
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/python/current/app/vespawatch/views.py", line 325, in single_individual_json
    return JsonResponse(get_object_or_404(Individual, pk=pk).as_dict())
  File "/opt/python/current/app/vespawatch/models.py", line 575, in as_dict
    'thumbnails': [x.thumbnail.url for x in self.pictures.all()],
  File "/opt/python/current/app/vespawatch/models.py", line 575, in <listcomp>
    'thumbnails': [x.thumbnail.url for x in self.pictures.all()],
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/__init__.py", line 85, in url
    return self._storage_attr('url')
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/__init__.py", line 75, in _storage_attr
    existence_required.send(sender=self, file=self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/registry.py", line 53, in existence_required_receiver
    self._receive(file, 'on_existence_required')
  File "/opt/python/run/venv/src/django-imagekit/imagekit/registry.py", line 61, in _receive
    call_strategy_method(file, callback)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/utils.py", line 166, in call_strategy_method
    fn(file)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/strategies.py", line 15, in on_existence_required
    file.generate()
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/__init__.py", line 94, in generate
    self.cachefile_backend.generate(self, force)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/backends.py", line 109, in generate
    self.generate_now(file, force=force)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/backends.py", line 96, in generate_now
    file._generate()
  File "/opt/python/run/venv/src/django-imagekit/imagekit/cachefiles/__init__.py", line 98, in _generate
    content = generate(self.generator)
  File "/opt/python/run/venv/src/django-imagekit/imagekit/utils.py", line 152, in generate
    content = generator.generate()
  File "/opt/python/run/venv/src/django-imagekit/imagekit/specs/__init__.py", line 153, in generate
    self.source.open()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 74, in open
    self.file = self.storage.open(self.name, mode)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/files/storage.py", line 33, in open
    return self._open(name, mode)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 464, in _open
    f = S3Boto3StorageFile(name, mode, self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/storages/backends/s3boto3.py", line 72, in __init__
    self.obj.load()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by bartaelterman** [comment]
@stijnvanhoey it's a `403: Forbidden`. So I guess the user doesn't have access to the bucket? I don't know how the credentials are managed. I assume we have an instance profile attached to the machine?  Is it attached correctly with the right permissions?

**Comment by stijnvanhoey** [comment]
Indeed, wrongly managed reference to S3 bucket during latest deployment. My mistake.

**Comment by peterdesmet** [comment]
They load in production.
