### ISSUE TITLE
Validation on the coordindates?

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#288]
The sync to inaturalist has been out for a couple of hours due to an error during synchronization:

```
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://www.inaturalist.org/observations.json

Traceback (most recent call last):
File "/opt/python/current/app/manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(*args, **options)
File "/opt/python/bundle/4/app/vespawatch/management/commands/inaturalist_sync.py", line 118, in handle
self.push_created(token)
File "/opt/python/bundle/4/app/vespawatch/management/commands/inaturalist_sync.py", line 56, in push_created
obs.create_at_inaturalist(access_token=access_token)
File "/opt/python/bundle/4/app/vespawatch/models.py", line 566, in create_at_inaturalist
r = create_observations(params=params, access_token=access_token)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/pyinaturalist/rest_api.py", line 171, in create_observations
response.raise_for_status()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
```

When checking the observation, some issues were apparent:
- there was no mail or telephone number provided
- the coordinates were not valid (2222 value for both longitude/latitude)

The mandatory fields + validation of the input needs further adjustments and improvement.

**Comment by stijnvanhoey** [comment]
yet another failure on the coordinates:
![image](https://user-images.githubusercontent.com/754862/58327043-d9d94100-7e2e-11e9-9c40-69cca8da7350.png)

**Comment by niconoe** [comment]
@stijnvanhoey : Is it correct does that it does block the sync of other observations?

If so, in additions to the improved validation we should also make sure such errors are properly logged but do not breaks the whole sync process.

**Comment by stijnvanhoey** [comment]
Yes, it does block the sync process. So, yes, it should not break the sync process.

**Comment by niconoe** [comment]
Just added some coordinates validation.

**Comment by niconoe** [comment]
Fixed 10 days ago, closing. Please reopen if the issue comes back.
