### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#323]
Sync error introduced with https://github.com/inbo/vespa-watch/pull/320:

[20190725_sync_log.txt](https://github.com/inbo/vespa-watch/files/3430541/20190725_sync_log.txt)

**Comment by niconoe** [comment]
Not sure it was introduced by #320, other probable causes being:

- temporary error at iNaturalist API
- old bug surfacing now because something in the data is a bit different 

I just added a `DEBUG` line in the sync log that should help clarifying what happens. Once its deployed, we'll have to look at the log again and continue from there.

**Comment by peterdesmet** [comment]
```
observation Nest 63106 was missing
observation Nest 63101 was missing
observation Nest 63108 was missing
Traceback (most recent call last):
File "/opt/python/current/app/manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(*args, **options)
File "/opt/python/bundle/11/app/vespawatch/management/commands/inaturalist_sync.py", line 136, in handle
self.check_all_missing(pulled_inat_ids)
File "/opt/python/bundle/11/app/vespawatch/management/commands/inaturalist_sync.py", line 116, in check_all_missing
self.check_missing_obs(obs)
File "/opt/python/bundle/11/app/vespawatch/management/commands/inaturalist_sync.py", line 100, in check_missing_obs
inat_obs_data = get_observation(observation.inaturalist_id)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/pyinaturalist/node_api.py", line 40, in get_observation
r = get_observations(params={'id': observation_id}, user_agent=user_agent)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/pyinaturalist/node_api.py", line 54, in get_observations
return r.json()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/requests/models.py", line 889, in json
self.content.decode(encoding), **kwargs
File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by niconoe** [comment]
I supposedly added DEBUG information in the sync script, but can't see its output in the log. To be investigated.

**Comment by peterdesmet** [comment]
The DEBUG info is now in the new log: 
[201907261100_sync_log.txt](https://github.com/inbo/vespa-watch/files/3434860/201907261100_sync_log.txt)

**Comment by niconoe** [comment]
Revisiting this... Do we still have such crashes during sync? If so, can I get an updated log?

**Comment by peterdesmet** [comment]
Yes, but not that error. 🤷‍♂

**Comment by niconoe** [comment]
Probably due to throttling issues and fixed recently while working on other sync issues (#371 and similiar)
