### ISSUE TITLE
Unserialisable models

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#364]
Some migration path was broken between revision app-e035d-191015_093933 | Send email to observer rather than test address (the one currently in production) and now, therefore any attemps to generate a new migration fails:

> Migrations for 'vespawatch':
  vespawatch/migrations/0035_auto_20200115_1146.py
    - Add field description_fr to identificationcard
    - Add field vernacular_name_fr to taxon
    - Alter field identification_picture on identificationcard
    - Alter field observation_time on individual
    - Alter field action_time on managementaction
    - Alter field duration on managementaction
    - Alter field person_name on managementaction
    - Alter field observation_time on nest
    - Alter field description on profile
    - Alter field email_notification on profile
    - Alter field organization on profile
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 184, in handle
    self.write_migration_files(changes)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 222, in write_migration_files
    migration_string = writer.as_string()
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/writer.py", line 151, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/writer.py", line 110, in serialize
    _write(arg_name, arg_value)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/writer.py", line 74, in _write
    arg_string, arg_imports = MigrationWriter.serialize(_arg_value)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/writer.py", line 279, in serialize
    return serializer_factory(value).serialize()
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/serializer.py", line 197, in serialize
    return self.serialize_deconstructed(path, args, kwargs)
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/serializer.py", line 85, in serialize_deconstructed
    arg_string, arg_imports = serializer_factory(arg).serialize()
  File "/Users/nicolas_noe/miniconda3/envs/vespa-watch/lib/python3.6/site-packages/django/db/migrations/serializer.py", line 353, in serializer_factory
    "topics/migrations/#migration-serializing" % (value, get_docs_version())
ValueError: Cannot serialize: <staticmethod object at 0x1060c2eb8>
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/2.1/topics/migrations/#migration-serializing

-> This needs to be solve before we can proceed with anything else
-> Q: which part exactly is not serializable
-> Q: why are all those other changes not already in a previous migration.

**Comment by niconoe** [comment]
Solved, this was due to the use of static methods in Models.py and apparently not directly related to other recent migration issues. Proceed carefully in production for the next steps anyway.
